variables:
    ROS_DISTRO: "kinetic"
    CI_SOURCE_PATH: "$CI_PROJECT_DIR"
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - docker info
    - mkdir docker
    - wget https://gitlab.mitre.org/dart-release/gitlabci-configs/-/raw/master/docker/kinetic/Dockerfile
    - wget https://gitlab.mitre.org/dart-release/gitlabci-configs/-/raw/master/docker/kinetic/ros_entrypoint.sh
    - chmod +x ros_entrypoint.sh
    - mv Dockerfile ros_entrypoint.sh docker/

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - docker build -t ros_${ROS_DISTRO}_kvh_geo_fog_3d -f docker/Dockerfile .
    tags:
        - docker-shell

pages:
  stage: deploy
  script:
    - rm -rf public/ || true
    - mkdir public/
    - docker rm ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen || true
    - docker run --name ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen -e ROS_DISTRO='${ROS_DISTRO}' ros_${ROS_DISTRO}_kvh_geo_fog_3d bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && cd catkin_ws/src && rosdoc_lite -o doc kvh_geo_fog_3d_driver"
    - docker cp ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen:/home/build/catkin_ws/src/doc/html/. public/
    - docker rm ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen
  tags:
    - docker-shell
  artifacts:
    paths:
      - public/
  only:
    - master
