variables:
    ROS_DISTRO: "melodic"
    CI_SOURCE_PATH: "$CI_PROJECT_DIR"
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - docker info

stages:
    - build

build:
    stage: build
    script:
        - docker build -t ros_${ROS_DISTRO}_kvh_geo_fog_3d -f docker/Dockerfile .
    tags:
        - docker-shell
