variables:
    ROS_DISTRO: "melodic"
    CI_SOURCE_PATH: "$CI_PROJECT_DIR"
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - docker info

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - docker build -t ros_${ROS_DISTRO}_kvh_geo_fog_3d -f docker/Dockerfile .
    tags:
        - docker-shell

pages:
  stage: deploy
  script:
    - docker run -it --name ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen ros_${ROS_DISTRO}_kvh_geo_fog_3d bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && cd catkin_ws/src && rosdoc_lite -o doc kvh_geo_fog_3d_driver"
    - docker cp ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen:/home/build/catkin_ws/src/doc/. public/
    - docker rm ros_${ROS_DISTRO}_kvh_geo_fog_3d_tmpdocgen
  tags:
    - docker-shell
  artifacts:
    paths:
      - public/
  only:
    - melodic-devel
