image:
    name: artifacts.mitre.org:8200/dart/dart_gitlab_runner_kinetic:latest
    entrypoint: ['bash', '-c', 'exec su gitlab -c bash']

variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/src/

stages:
    - build

build:
    stage: build
    tags:
        - docker
    script:
        - echo ${PWD}
        - echo "Trying to build with catkin..."
        - catkin build